jobs:
  build:
    docker:
      - image: circleci/php:8.0.11

    steps:
      - checkout
      - sonarcloud/scan:
          sonar_token_variable_name: SONAR_TOKEN 
      
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

version: 2.1
workflows:
  main:
    jobs:
      - build:
          context: sonarcloud